# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tripbudget
spring.datasource.username=ashok25
spring.datasource.password=Dhathri@25
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT properties
jwt.secret=mySuperSecretKeyWithAtLeast256BitsForHMACSHA256SignatureVerification
jwt.expirationMs=86400000

# Server port
server.port=8080
